language: node_js
node_js:
  - '11'
dist: Bionic
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- ng build --prod --base-href https://typhon0.github.io/whatdoweplay/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/whatdoweplay
  on:
    branch: master